### ISSUE TITLE
Minor typo at `01_struct.toml#L70`; `istead` -> `instead`

### ISSUE THREAD

**Issue by Delta456** [rusinikita/trainer#8]
https://github.com/rusinikita/trainer/blob/57a5449b57c39e993c0f2caf354bec0d0f27cd2b/challenge/files/01_structs.toml#L70

As you can see there's a minor typo here. It should be `instead` instead of `istead`.

**Comment by Delta456** [comment]
Can make PR if required

**Comment by rusinikita** [comment]
@Delta456 Thanks for that finding. I will fix that soon.
